#
# compiler and compiling profile
#
FCOMP=GNU          # options: GNU, INTEL, INTEL_IFORT, NVIDIA, CRAY, FUJITSU
FFLAGS_OPT=1       # for production runs
FFLAGS_OPT_MAX=0   # for production runs (more aggressive optimization)
FFLAGS_DEBUG=0     # for debugging
FFLAGS_DEBUG_MAX=0 # for thorough debugging
#
# defines
#
SINGLE_PRECISION=0       # perform the whole calculation in single precision
TIMING=0                 # report wall-clock time per time step
IMPDIFF=0                # implicit discretization of the diffusion terms
BOUSSINESQ_BUOYANCY=0    # Boussinesq source term from the first scalar field
FFT_AXIS=3               # options: 0 (off), 1 (_FFT_X), 2 (_FFT_Y), 3 (_FFT_Z)
FFT_USE_SLABS=0          # use slab communication for the FFT path
FFT_USE_SLICED_PENCILS=0 # use sliced pencils for the FFT path
ONE_PRESS_CORR=0         # use one pressure correction when possible
OPENMP=0                 # OpenMP build
