name: compilation test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    - name: install software
      run: |
        sudo apt-get update; sudo apt-get install gfortran libopenmpi-dev git libfftw3-dev
        git clone https://github.com/hypre-space/hypre $HOME/hypre_repo && cd $HOME/hypre_repo/src && ./configure --prefix=$HOME/hypre && make && make install && cd -
    - name: test compilation
      run: |
        export LD_LIBRARY_PATH="${HOME}/hypre/lib:${LD_LIBRARY_PATH}"
        make HYPRE_LIB_DIR="${HOME}/hypre/lib" FFT_AXIS=0 run && make clean
        make HYPRE_LIB_DIR="${HOME}/hypre/lib" OPENMP=1 IMPDIFF=1 FFT_AXIS=0 run && make clean
        make HYPRE_LIB_DIR="${HOME}/hypre/lib" OPENMP=1 IMPDIFF=1 FFT_AXIS=3 run && make clean
